cmake_minimum_required(VERSION 3.5)
project(vgui1)
set(CMAKE_CXX_STANDARD 11)
file(GLOB VGUI_SOURCES "src/*.cpp")
add_library(vgui STATIC ${VGUI_SOURCES})
target_include_directories(vgui PUBLIC /projects/sandbox/vgui-dev-study/include)
if(NOT MSVC)
    target_compile_options(vgui PRIVATE -fvisibility=default -Wno-unused-parameter)
endif()
