/*
embedded_font.cpp - thin wrapper around the auto-generated byte array
Copyright (c) 2026 DragonSlayer Team
*/

#include "embedded_font.h"

#include <stddef.h>
#include <stdio.h>
#include <string.h>

extern "C" {
extern const unsigned char g_embeddedFontData[];
extern const unsigned int  g_embeddedFontLen;
extern const char          g_embeddedFontName[];
}

// Build the gfx/fonts/<lower(name)>.ttf path the way FindFontDataFile()
// does for any unknown font name. Kept in sync with the generic-fallback
// branch in FontManager::FindFontDataFile so a path produced there will
// match here. The transformation is: lowercase ASCII, ' ' -> '_', other
// chars passed through unchanged.
static void BuildExpectedPath( char *out, size_t out_size )
{
	if ( out_size == 0 )
		return;
	out[0] = 0;
	if ( !g_embeddedFontName[0] )
		return;

	char lower[64];
	size_t li = 0;
	for ( ; g_embeddedFontName[li] && li + 1 < sizeof( lower ); li++ )
	{
		char c = g_embeddedFontName[li];
		if ( c >= 'A' && c <= 'Z' )      lower[li] = (char)(c - 'A' + 'a');
		else if ( c == ' ' )              lower[li] = '_';
		else                              lower[li] = c;
	}
	lower[li] = 0;

	snprintf( out, out_size, "gfx/fonts/%s.ttf", lower );
}

bool Embedded_PathMatches( const char *vfspath )
{
	if ( !vfspath || g_embeddedFontLen == 0 || !g_embeddedFontName[0] )
		return false;

	char expected[80];
	BuildExpectedPath( expected, sizeof( expected ) );
	return expected[0] && strcmp( vfspath, expected ) == 0;
}

unsigned char *Embedded_GetData( int *plen )
{
	if ( g_embeddedFontLen == 0 )
	{
		if ( plen ) *plen = 0;
		return NULL;
	}
	if ( plen ) *plen = (int)g_embeddedFontLen;
	// Caller MUST NOT free this - it points into static const memory.
	return (unsigned char *)g_embeddedFontData;
}
