#!/usr/bin/env python3
"""Generate font/embedded_font_data.cpp from a TTF source.

The byte array gets compiled into libmenu.so so the menu always has a
usable font without any dependency on the game directory or APK assets.
The "logical name" is the slot name TrackerScheme.res uses to refer to
the font (e.g. "Tahoma"); the actual rendered glyphs come from whatever
TTF was last passed to this script.

Usage:
    cd mainui_cpp/font/embedded_source
    python3 gen_embedded.py source.ttf "Tahoma"

Effect:
    Writes ../embedded_font_data.cpp with the byte array.
    Recompile libmenu.so to pick up the change.

Drop your own licensed Tahoma at source.ttf and rerun to swap fonts.
The script does NOT touch metadata - it just embeds whatever bytes you
give it. The internal TTF 'name' table inside the bytes is what the
font really is; the logical name passed here is just the lookup key
used by the engine's FontManager.
"""
import os
import sys


def gen(ttf_path: str, out_cpp: str, font_logical_name: str) -> None:
    with open(ttf_path, "rb") as f:
        data = f.read()
    n = len(data)
    if n <= 0:
        raise SystemExit(f"empty TTF: {ttf_path}")

    safe_name = font_logical_name.replace('"', '\\"')
    with open(out_cpp, "w") as o:
        o.write("// Auto-generated by font/embedded_source/gen_embedded.py - DO NOT EDIT.\n")
        o.write(f"// Source: {os.path.basename(ttf_path)} ({n} bytes)\n")
        o.write(f'// Logical slot name in TrackerScheme.res: "{safe_name}"\n')
        o.write("// Actual rendered glyphs come from the TTF named above; consult the\n")
        o.write("// internal 'name' table of the original TTF if you want to know what\n")
        o.write("// designer/family is really inside.\n\n")
        o.write("#include <stddef.h>\n\n")
        o.write('extern "C" {\n')
        o.write(f"const unsigned char g_embeddedFontData[{n}] = {{\n")
        for i in range(0, n, 16):
            chunk = data[i:i + 16]
            line = ", ".join("0x%02X" % b for b in chunk)
            o.write("    " + line)
            if i + 16 < n:
                o.write(",")
            o.write("\n")
        o.write("};\n")
        o.write(f"const unsigned int g_embeddedFontLen  = {n};\n")
        o.write(f'const char         g_embeddedFontName[] = "{safe_name}";\n')
        o.write('} // extern "C"\n')
    print(f"-> {out_cpp}: {n} bytes embedded as logical font \"{font_logical_name}\"")


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    ttf = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "source.ttf")
    name = sys.argv[2] if len(sys.argv) > 2 else "Tahoma"
    out = os.path.normpath(os.path.join(here, "..", "embedded_font_data.cpp"))
    gen(ttf, out, name)
